dist: trusty
sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake-3.10
script:
- mkdir build
- cd build
- cmake ..
- make 
- ctest
