#xenial distro required for cmake version 3.10+
dist: bionic
sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
env:
- MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
script:
- mkdir build
- cd build
- cmake ..
- make 
- ctest
