#xenial distro required for cmake version 3.10+
dist: xenial
sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
script:
- mkdir build
- cd build
- cmake ..
- make 
- ctest
